# Generated by Django 5.0.6 on 2024-05-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categories_options'),
        ('store', '0002_alter_categories_options_product_is_sale_and_more'),
    ]

    operations = [
    ]
